parameters:                       #This value will use default one if there is no parameters passed into this template
  buildConfiguration: 'Release'
  project: ''

steps:        
  - task: DotNetCoreCLI@2
    displayName: 'Build the project - ${{ parameters.buildConfiguration }}'
    inputs:
      command: build
      arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
      projects: '${{ parameters.project }}'

  - task: DotNetCoreCLI@2
    displayName: 'Publish the project - ${{ parameters.buildConfiguration }}'
    inputs:
      command: publish    #publish build results (including its dependencies)
      projects: '${{ parameters.project }}'
      publishWebProjects: false   #Build.ArtifactStagingDirectory is the folder storing artifact in azure devops
      arguments:  '--no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}'
      zipAfterPublish:  true      #Zip the whole project folder into zip file